#!/usr/bin/env bash
# kanka-mcp quickstart: install deps, build, prompt for credentials, run smoke test.
# Idempotent — re-running reuses previous credentials unless you opt to re-enter.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
cd "$REPO_DIR"

if [ -t 1 ]; then
  BOLD=$'\033[1m'; DIM=$'\033[2m'; GREEN=$'\033[32m'; RED=$'\033[31m'
  YELLOW=$'\033[33m'; CYAN=$'\033[36m'; RESET=$'\033[0m'
else
  BOLD=""; DIM=""; GREEN=""; RED=""; YELLOW=""; CYAN=""; RESET=""
fi

step() { printf '\n%s==> %s%s\n' "${BOLD}${CYAN}" "$*" "${RESET}"; }
ok()   { printf '%s✓%s %s\n' "${GREEN}" "${RESET}" "$*"; }
warn() { printf '%s!%s %s\n' "${YELLOW}" "${RESET}" "$*"; }
fail() { printf '%s✗ %s%s\n' "${RED}" "$*" "${RESET}" >&2; exit 1; }

cat <<EOF

${BOLD}kanka-mcp quickstart${RESET}
${DIM}install → build → authenticate → verify${RESET}

EOF

# 1. Prereqs
step "Checking prerequisites"
command -v node >/dev/null 2>&1 || fail "Node.js not found. Install Node 20+ from https://nodejs.org/"
NODE_MAJOR=$(node -p 'process.versions.node.split(".")[0]')
if [ "$NODE_MAJOR" -lt 20 ]; then
  fail "Node.js 20+ required (you have $(node --version))"
fi
ok "node $(node --version)"

# 2. Install
step "Installing dependencies"
npm install --no-audit --no-fund --silent
ok "Dependencies installed"

# 3. Build
step "Building TypeScript"
npm run build --silent
ok "Built dist/"

# 4. Auth method
step "Choose authentication method"
cat <<EOF

  ${BOLD}1)${RESET} Personal API token  ${DIM}— simplest, recommended for solo use${RESET}
  ${BOLD}2)${RESET} OAuth 2.0           ${DIM}— refreshable; needs an OAuth client registered with Kanka${RESET}

EOF
read -rp "Selection [1]: " AUTH_CHOICE
AUTH_CHOICE=${AUTH_CHOICE:-1}

TOKEN_FILE="$HOME/.config/kanka-mcp/token"
ENV_FILE="$REPO_DIR/.env"

case "$AUTH_CHOICE" in
  1)
    # ─── Personal API token ──────────────────────────────────────────
    if [ -f "$TOKEN_FILE" ]; then
      warn "Existing token at $TOKEN_FILE"
      read -rp "Reuse it? [Y/n]: " REUSE
      if [[ "${REUSE:-Y}" =~ ^[Nn] ]]; then rm -f "$TOKEN_FILE"; fi
    fi
    if [ ! -f "$TOKEN_FILE" ]; then
      cat <<EOF

Get your token at: ${CYAN}https://app.kanka.io/settings/api${RESET}
${DIM}(Kanka shows the value once — save it before clicking away.)${RESET}

EOF
      read -rsp "Paste your Personal API token (input hidden): " KANKA_TOKEN_INPUT
      echo
      [ -n "${KANKA_TOKEN_INPUT:-}" ] || fail "Empty token"
      mkdir -p "$(dirname "$TOKEN_FILE")"
      printf '%s' "$KANKA_TOKEN_INPUT" > "$TOKEN_FILE"
      chmod 600 "$TOKEN_FILE"
      unset KANKA_TOKEN_INPUT
      ok "Wrote $TOKEN_FILE (mode 0600)"
    fi

    step "Running smoke test"
    npm run smoke

    cat <<EOF

${BOLD}MCP client config snippet${RESET} ${DIM}(token resolved automatically from $TOKEN_FILE; tier auto-detected via /profile on startup)${RESET}

  ${DIM}# Claude Desktop — add under "mcpServers":${RESET}
  "kanka": {
    "command": "node",
    "args": ["$REPO_DIR/dist/index.js"]
  }

  ${DIM}# Claude Code CLI:${RESET}
  claude mcp add kanka -- node $REPO_DIR/dist/index.js

EOF
    ;;

  2)
    # ─── OAuth 2.0 ────────────────────────────────────────────────────
    if [ -f "$ENV_FILE" ]; then
      warn "Existing OAuth credentials at $ENV_FILE"
      read -rp "Reuse them? [Y/n]: " REUSE
      if [[ "${REUSE:-Y}" =~ ^[Nn] ]]; then rm -f "$ENV_FILE"; fi
    fi

    if [ ! -f "$ENV_FILE" ]; then
      cat <<EOF

Register an OAuth client at: ${CYAN}https://app.kanka.io/settings/api?clients=1${RESET}

  ${BOLD}Name${RESET}:         anything (this is just a label)
  ${BOLD}Redirect URI${RESET}: ${CYAN}http://localhost:53117/cb${RESET}
                ${DIM}(use 'localhost' — Kanka rejects raw 127.0.0.1)${RESET}

After saving, Kanka issues you a numeric ${BOLD}Client ID${RESET} (e.g. 102) and a ${BOLD}Client Secret${RESET}.
${YELLOW}!${RESET} The Client ID is NOT the name you typed — it's the value Kanka generated.

EOF
      read -rp "Client ID (numeric, e.g. 102): " CLIENT_ID
      [ -n "${CLIENT_ID:-}" ] || fail "Empty client ID"
      read -rsp "Client Secret (input hidden): " CLIENT_SECRET
      echo
      [ -n "${CLIENT_SECRET:-}" ] || fail "Empty client secret"
      read -rp "Redirect port [53117]: " PORT
      PORT=${PORT:-53117}

      umask 077
      cat > "$ENV_FILE" <<ENVEOF
# kanka-mcp OAuth credentials. Generated by quickstart.sh.
# This file is gitignored. Do not commit.
KANKA_OAUTH_CLIENT_ID=$CLIENT_ID
KANKA_OAUTH_CLIENT_SECRET=$CLIENT_SECRET
KANKA_OAUTH_REDIRECT_PORT=$PORT
ENVEOF
      chmod 600 "$ENV_FILE"
      unset CLIENT_ID CLIENT_SECRET
      ok "Wrote $ENV_FILE (mode 0600)"
    else
      # shellcheck disable=SC1090
      source "$ENV_FILE"
      PORT="${KANKA_OAUTH_REDIRECT_PORT:-53117}"
    fi

    step "Running OAuth login + smoke test"
    warn "Your browser will open. Click 'Authorize' on the Kanka consent screen."
    npm run smoke -- --oauth

    cat <<EOF

${BOLD}MCP client config snippet${RESET} ${DIM}(reads credentials from $ENV_FILE for local; copy values for remote clients. Tier auto-detected via /profile.)${RESET}

  ${DIM}# Claude Desktop — add under "mcpServers":${RESET}
  "kanka": {
    "command": "node",
    "args": ["$REPO_DIR/dist/index.js"],
    "env": {
      "KANKA_OAUTH_CLIENT_ID": "<from .env>",
      "KANKA_OAUTH_CLIENT_SECRET": "<from .env>",
      "KANKA_OAUTH_REDIRECT_PORT": "$PORT"
    }
  }

EOF
    ;;

  *)
    fail "Invalid selection: $AUTH_CHOICE (expected 1 or 2)"
    ;;
esac

cat <<EOF

${GREEN}${BOLD}✓ Setup complete.${RESET}

  ${BOLD}Re-run smoke:${RESET}     npm run smoke
  ${BOLD}With CRUD test:${RESET}   npm run smoke -- --mutate
  ${BOLD}Logout (OAuth):${RESET}   delete ~/.config/kanka-mcp/oauth.json
  ${BOLD}Reset all:${RESET}        delete .env and ~/.config/kanka-mcp/

EOF
